### ISSUE TITLE
Problems with Plugin "admin columns"

### ISSUE THREAD

**Issue by BerlinMrProper** [hofmannsven/mark-posts#29]
For me, Mark-Posts is a very important plugin and there is hardly anything comparable. Unfortunately it does not work with the well-known “admin columns” plugin. On my server I always get the error message "Undefined array key 12 in /var/www/vhosts/*********.com/httpdocs/wp-content/plugins/mark-posts/admin/views/admin. php on line 124" as soon as you want to save something in the settings. In the admin area, the highlights are not displayed for active "admin columns".
Maybe your fans can hope that you'll take a look at the combination with "admin colums"? We need your plugin!!!

**Steps to reproduce the issue**
- Plugin Version: 2.2.2
- WordPress Version: 6.1.4
- PHP Version: 8.0.27
- Avada 7.11.3 Theme
- Browser and operating system: Opera, Firefox, Chrome, Safari, Windows 10 & MAC OSX

**Comment by hofmannsven** [comment]
@BerlinMrProper Thank you for reporting this issue. I fixed the error with the undefined array key in the latest version of the plugin.

I couldn't find any issues with the interaction between the Codepress Admin Columns plugin and the Avada theme, though. I was able to select _Marker_ from the _Types_ for _Pages_:

![Screenshot: Codepress Admin Columns plugin settings](https://github.com/hofmannsven/mark-posts/assets/1214387/c4d615ac-1f45-408b-b8de-4f63e49e224f)

Can you please describe in more detail what is not working for you?

**Comment by hofmannsven** [comment]
@BerlinMrProper Thanks for the positive feedback. I'm glad I could help.
